sudo: true
language: ruby
rvm:
  - '2.0'
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - jruby-9.1.5.0
matrix:
    allow_failures:
        - rvm: jruby-9.1.5.0

cache: bundler

install:
    - git config --global user.name "Autoproj on Travis CI"
    - git config --global user.email "autoproj@travis"
    - gem install bundler
    # Some tests expect gems to be present in vendor/bundle
    - bundler install --path vendor/bundle
script:
    - bundler exec rake
    - AUTOPROJ_SKIP_LONG_TESTS=1 bundler exec rake test
